/* eslint-disable camelcase */
import type { Metadata } from 'next';
import '../../scss/global.scss';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { NextIntlClientProvider, useMessages, useTranslations } from 'next-intl';
import { unstable_setRequestLocale } from 'next-intl/server';
import { LocaleSwitcher } from '@/components/LocaleSwitcher';
/**
 *
 */

/**
 *
 */
export default function RootLayout(props: { children: React.ReactNode; params: { locale: string } }) {
  unstable_setRequestLocale(props.params.locale);
  const t = useTranslations('Common');
  // Using internationalization in Client Components
  const messages = useMessages();
  return (
    <html lang={props.params.locale}>
      <body>
        <p>{t('Hello')}</p>
        <NextIntlClientProvider locale={props.params.locale} messages={messages}>
          {props.children}
          <LocaleSwitcher />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
